services:
  - type: web
    name: classement-api
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: classement-db
          property: connectionString

  - type: cron
    name: update-data
    schedule: "*/30 * * * *"
    buildCommand: |
      pip install --no-cache-dir --force-reinstall -r requirements.txt
    startCommand: python ExtractAllDataPostgres.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: classement-db
          property: connectionString

databases:
  - name: classement-db
    plan: free