services:
  - type: web
    name: classement-api
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: classement-db
          property: connectionString

  - type: cron
    name: update-data
    region: frankfurt
    runtime: python
    schedule: "*/30 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python ExtractAllDataPostgres.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: classement-db
          property: connectionString

databases:
  - name: classement-db
    region: frankfurt
    plan: free
