using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JessyProject.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
       protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.Sql(@"
        DO $$
        BEGIN
            -- Création du schéma conditionnelle
            IF NOT EXISTS (
                SELECT 1 FROM pg_namespace WHERE nspname = 'c2e'
            ) THEN
                CREATE SCHEMA c2e;
            END IF;

            -- Création table Bouygues
            IF NOT EXISTS (
                SELECT 1 
                FROM pg_tables 
                WHERE schemaname = 'c2e' 
                AND tablename = 'bouygues' -- PostgreSQL est case-sensitive
            ) THEN
                CREATE TABLE c2e.""Bouygues"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""Date"" timestamp without time zone NOT NULL,
                    ""Num_contrat"" character varying(50) NOT NULL,
                    ""Vendeur"" character varying(100),
                    ""Status"" character varying(50),
                    ""Client"" character varying(255),
                    ""Produite"" character varying(50),
                    ""Equipe"" character varying(100),
                    PRIMARY KEY (""Id"")
                );
            END IF;

            -- Ajouter les autres tables avec le même pattern...
            
            -- Création des index conditionnels
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE schemaname = 'c2e' 
                AND tablename = 'bouygues' 
                AND indexname = 'Bouygues_Num_contrat_key'
            ) THEN
                CREATE UNIQUE INDEX ""Bouygues_Num_contrat_key"" ON c2e.""Bouygues"" (""Num_contrat"");
            END IF;

        END $$;
    ");
}

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Bouygues",
                schema: "c2e");

            migrationBuilder.DropTable(
                name: "Engie",
                schema: "c2e");

            migrationBuilder.DropTable(
                name: "Ohm",
                schema: "c2e");
        }
    }
}
