// <auto-generated />
using System;
using JessyProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JessyProject.Data.Migrations
{
    [DbContext(typeof(ClassementDbContext))]
    partial class ClassementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("c2e")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JessyProject.Models.Bouygues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("client")
                        .IsFixedLength();

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("equipe")
                        .IsFixedLength();

                    b.Property<string>("NumContrat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Num_contrat");

                    b.Property<string>("Produite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("produite")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status")
                        .IsFixedLength();

                    b.Property<string>("Vendeur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vendeur")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_bouygues");

                    b.HasIndex("NumContrat", "Produite")
                        .IsUnique()
                        .HasDatabaseName("ix_bouygues_unique_contrat");

                    b.ToTable("Bouygues", "c2e");
                });

            modelBuilder.Entity("JessyProject.Models.Engie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<string>("Equipe")
                        .HasMaxLength(255)
                        .HasColumnType("character(255)")
                        .IsFixedLength();

                    b.Property<string>("NumContrat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Num_contrat");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<string>("Vendeur")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC07F4414995");

                    b.ToTable("Engie", "c2e");
                });

            modelBuilder.Entity("JessyProject.Models.Ohm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<string>("Equipe")
                        .HasMaxLength(255)
                        .HasColumnType("character(255)")
                        .IsFixedLength();

                    b.Property<string>("NumContrat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Num_contrat");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.Property<string>("Vendeur")
                        .HasMaxLength(50)
                        .HasColumnType("character(50)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC07AAD91352");

                    b.ToTable("Ohm", "c2e");
                });
#pragma warning restore 612, 618
        }
    }
}
